In [7]:
import numpy as np 


x = np.fromfunction(lambda x,y : x == y, (2,3))
print(x)
x= x * 1
x

[[ True False False]
 [False  True False]]


array([[1, 0, 0],
       [0, 1, 0]])

In [8]:
l1 = [1,1,23,1,3,12]

np.asarray(l1)

array([ 1,  1, 23,  1,  3, 12])

In [18]:
np.zeros((3,2,3))  # 3d 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones((2,2)) # 2d 
10 *np.ones(5) # 1D

array([10., 10., 10., 10., 10.])

In [21]:
3 * np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.39911598e-321, 1.24610723e-306,
        1.29061142e-306]])

In [35]:
np.linspace(1,10,3) # 3 no between this numbers  # 1d array but we can convert into 2d 

array([ 1. ,  5.5, 10. ])

In [44]:
np.linspace(1,5,10,endpoint=False).reshape(2,5) # 2d now  endpoint 6 will not come

array([[1. , 1.4, 1.8, 2.2, 2.6],
       [3. , 3.4, 3.8, 4.2, 4.6]])

In [45]:
np.linspace(1,5,10,endpoint=False,retstep=True)

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)

In [49]:
np.logspace(1,10,5,base=2)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [51]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
3 * 6 * 2

36

In [71]:
a = np.arange(4,20).reshape(2,4,2)

In [72]:
a.max(axis=1)

array([[10, 11],
       [18, 19]])

In [94]:
b = np.arange(1,10).reshape(3,3)
print(b)
print()
print(b.max(axis=1))
print()
print(b.max(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6 9]

[7 8 9]


In [118]:
c = np.arange(15).reshape(3,5)

# Row wise Broadcasting like this 

d = np.array([1,2,4,6,7])
print(c)
e = d +c
e

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 1,  3,  6,  9, 11],
       [ 6,  8, 11, 14, 16],
       [11, 13, 16, 19, 21]])

In [135]:
d = np.array([1,2,4,])

d=d.reshape(1,-1)
d1 = d.T 
d1

array([[1],
       [2],
       [4]])

In [136]:
print(c)
c+d1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [14, 15, 16, 17, 18]])

In [137]:
np.sqrt(d)

array([[1.        , 1.41421356, 2.        ]])

In [138]:
np.log(d)

array([[0.        , 0.69314718, 1.38629436]])

In [139]:
np.log10(d)

array([[0.        , 0.30103   , 0.60205999]])

In [146]:
# Deep Copy and Shallow Copy 

d = np.array([1,23,2,3,2,3])
a = d   #  Shallow Copy

d1 = d.copy()   # Deep Copy
print("")

d[0] = 100
a

array([100,  23,   2,   3,   2,   3])

In [149]:
id(a)  # it will return the identidy of obj

2331784851120

In [ ]:
#
np.zeros   # to create zero array
np.ones  # to create one array # we can give a shape also
np.empty  # to create a random array
np.logspace  #to create log base result based on some range 
np.linspace # to create based on specified number range and what number you expect ex : np.linspace(1,4,2)
np.arange(number).reshape # to give a specified 2d shape result 


# We can do addition and multiplication based 
# remind all must have same shape and size and also see the 1d and 2d Thing 
np.log()
np.sqrt()
np.log()
