In [4]:
import pandas as pd 

In [24]:
df= pd.DataFrame({
    "col1" : [1,2,3],
    "col" : ["12","Sw3","ss"],
    "Prakash" :"Pra ss ss".split()
})

In [25]:
df.head()


df['col5'] = df['col1']**2

df

col1  col Prakash  col5
0     1   12     Pra     1
1     2  Sw3      ss     4
2     3   ss      ss     9

In [30]:
df['col6'] = df['Prakash'].str[0]
df['col6'].apply(test)

0     P
1    Ay
2    Ay
Name: col6, dtype: object

In [33]:
def test(df):
    if df != 'Pra':
        return 'Ay'
    else:
        return 'Pra'

In [31]:
# Why we are using external function you can try with lambda 

In [36]:
df['Ne'] = df['Prakash'].apply(lambda df : "Ay" if df != 'Pra' else 'Pra' )

In [39]:
df['Length']  = df['Prakash'].apply(len)
df

col1  col Prakash  col5 col6   Ne  Length
0     1   12     Pra     1    P  Pra       3
1     2  Sw3      ss     4    s   Ay       2
2     3   ss      ss     9    s   Ay       2

In [42]:
import math 


df['log'] = df['col5'].apply(math.log)
df

col1  col Prakash  col5 col6   Ne  Length       log
0     1   12     Pra     1    P  Pra       3  0.000000
1     2  Sw3      ss     4    s   Ay       2  1.386294
2     3   ss      ss     9    s   Ay       2  2.197225

In [1]:
import numpy as np

In [7]:
# Array equivalent to List 

l1 = [1,3,2,32,232]
np.array(l1)


array([  1,   3,   2,  32, 232])

In [8]:
type(np.array(l1))

numpy.ndarray

In [14]:
d1 = np.array([1,2.3,44,42])
d1[2]

44.0

In [13]:
d=np.array([[1,2],[1,2]])
d[1][1]

2

In [25]:
np.array(l1,ndmin=3)[0][0][0]

1

In [26]:
np.asanyarray([1,2,3,3])

array([1, 2, 3, 3])

In [27]:
np.mat([1,2,3,2,3]) # 2dim by def

matrix([[1, 2, 3, 2, 3]])

In [28]:
np.array(np.mat([1,2,3,2]))

array([[1, 2, 3, 2]])

In [30]:
np.fromfunction(lambda x,y : x == y,(4,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [37]:
np.fromfunction(lambda x,y,z : x * y * z,(4,3,3),dtype=int)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12]]])

In [ ]:
np.array() # Creates a array which is similar to list but array and matrix were mostly used in ai 
# array can give us dimension thing which was not possible in list \
# Inside we can also provide ndimension = 1,2,3
np.array(listthing,ndmin=2)
# Accessing is also easy 
np.array(listthing) # bASED ON DIMENION WE CAN ACCESS SUCH AS 
np.array(listthing)[0][1]
np.asanyarray() # and 
np.asarray # are child of np.array works the same 
np.mat() # which is used to create matrix which support 2D
np.fromfunction # which will take function and create a array for you

In [46]:
np.fromfunction(lambda x,y,z,i : x *y*z * i ,(2,3,2,3),dtype=int) # If i try to convert into matrix it will through a error 

array([[[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 1, 2]],

        [[0, 0, 0],
         [0, 2, 4]]]])

In [59]:
A  = np.fromfunction(functionss,(3,4))

In [47]:
def functionss(a,b):
    return a *b

In [49]:
a = np.fromfunction(lambda x,y,z : x * y * z,(4,3,3),dtype=int)

a.ndim

3

In [50]:
a.size

36

In [54]:
a.shape,a.dtype

((4, 3, 3), dtype('int32'))

In [60]:
import pandas as pd 
pd.DataFrame(A)

0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  1.0  2.0  3.0
2  0.0  2.0  4.0  6.0

In [67]:
np.random.rand(3,3)

array([[0.40047279, 0.57941844, 0.93463748],
       [0.5834349 , 0.11077027, 0.34520586],
       [0.08781254, 0.82225971, 0.94781266]])

In [69]:
np.random.randn(2,3)

array([[ 0.91568011,  0.51748158, -0.97956615],
       [ 2.27972171, -1.07517198, -1.56555936]])

In [89]:
np.random.randint(3,33)

29

In [96]:
val = np.fromfunction(lambda x,y,z : x * y * z ,(3,2,3),dtype=int) # this we will try to reshape and convert into dataframe 
val
print(val)
print(val.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 2]]

 [[0 0 0]
  [0 2 4]]]
(3, 2, 3)


In [100]:
df = pd.DataFrame(val.reshape(3,6))
df.head()

0  1  2  3  4  5
0  0  0  0  0  0  0
1  0  0  0  0  1  2
2  0  0  0  0  2  4

In [107]:
val.reshape(3,-1) # -1 rest of all the element 
val.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 0, 0, 0, 0, 2, 4]])

In [108]:
# Range similar function 

list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
np.arange(1,10,.3) # with jump of float value range not support jump in float 

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

In [113]:
np.arange(1,4.0)[0:]


array([1., 2., 3.])

In [120]:
x = np.random.rand(4,4)

x[x > .5]

array([0.57758275, 0.69695246, 0.62847901, 0.58212324, 0.70714002,
       0.63847139])

In [139]:
print(x)
x[[1,2],[2]]

[[0.57758275 0.39886972 0.69695246 0.62847901]
 [0.58212324 0.32614921 0.70714002 0.45704441]
 [0.21540798 0.02183979 0.35778091 0.23535681]
 [0.42027554 0.63847139 0.20837404 0.10226108]]


array([0.70714002, 0.35778091])

In [149]:
x = np.random.rand(4,5)
print(x)
x[1:4,0:3]


[[0.55604104 0.70092001 0.68754848 0.37384464 0.77763614]
 [0.33390786 0.7623128  0.30923241 0.75785646 0.77475526]
 [0.01275027 0.63668743 0.5514343  0.05590829 0.56024138]
 [0.86597026 0.08065318 0.34598947 0.12092885 0.25238659]]


array([[0.33390786, 0.7623128 , 0.30923241],
       [0.01275027, 0.63668743, 0.5514343 ],
       [0.86597026, 0.08065318, 0.34598947]])

In [156]:
#exact same thing like this also ''

x[1:4,[0,1,2]]

array([[0.33390786, 0.7623128 , 0.30923241],
       [0.01275027, 0.63668743, 0.5514343 ],
       [0.86597026, 0.08065318, 0.34598947]])

In [161]:
a1 = x[1:4,[0,1,2]]

# replacing any element
a1[0][0] = 2.3333

a1 # overide any kind of element

array([[2.3333    , 0.7623128 , 0.30923241],
       [0.01275027, 0.63668743, 0.5514343 ],
       [0.86597026, 0.08065318, 0.34598947]])

In [169]:
x = np.array([[1,2],[2,4]])
y = np.array([[2,1],[4,3]])

print(x)
print(y)
x * y # element by multiplication


[[1 2]
 [2 4]]
[[2 1]
 [4 3]]


array([[ 2,  2],
       [ 8, 12]])

In [175]:
x = np.mat([[1,2],[2,4]])
y = np.mat([[2,1],[4,3]])
print(x)
print(y)
x @ y  # same result  @ matrix multiplication

[[1 2]
 [2 4]]
[[2 1]
 [4 3]]


matrix([[10,  7],
        [20, 14]])

In [178]:
2 * 1 + 4 * 3

14

In [174]:
val = x @ y/0
# it will not through error but it will give inf
val  

C:\Users\Admin\AppData\Local\Temp\ipykernel_14804\2621257534.py:1: RuntimeWarning: divide by zero encountered in divide
  val = x @ y/0


matrix([[inf, inf],
        [inf, inf]])